spring:
    application:
        name: researchlnkAPI
    datasource:
        url: jdbc:mysql://localhost:3306/researchlnk?createDatabaseIfNotExist=true
        username: root
        password: MyPassword!
    jpa:
        show-sql: true

#default username and password
    security:
        user:
            name: user
            password: password

#ORCID OAUTH2 config
        oauth2:
            client:
                registration:
                    orcid:
                        client-id: APP-PAC2MBBBAYC5U6ZP
                        client-secret: 107b5c94-65a5-4186-a5de-1ad6df708d30
                        scope: openid
                        authorization-grant-type: authorization_code
                        redirect-uri: "https://exact-horse-nearby.ngrok-free.app/login/oauth2/code/orcid"
                provider:
                    orcid:
                        authorization-uri: https://sandbox.orcid.org/oauth/authorize
                        token-uri: https://sandbox.orcid.org/oauth/token
                        user-info-uri: https://pub.sandbox.orcid.org/oauth/userinfo
                        user-name-attribute: sub
                        jwk-set-uri: https://sandbox.orcid.org/oauth/jwks

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
        org.springframework.web.client.RestTemplate: DEBUG







