spring:
    application:
        name: researchlnkAPI
    datasource:
        url: jdbc:mysql://localhost:3306/researchlnk?createDatabaseIfNotExist=true
        username: root
        password: MyPassword!
    jpa:
        show-sql: true

#default username and password
    security:
        user:
            name: user
            password: password

#ORCID OAUTH2 config
        oauth2:
            client:
                registration:
                    orcid:
                        client-id: APP-FPBF4JH03KFK1UGQ
                        client-secret: a5cf2a80-c16c-41db-af93-3a8b90128439
                        scope: /authenticate
                        authorization-grant-type: authorization_code
                        redirect-uri: "https://exact-horse-nearby.ngrok-free.app/login/oauth2/code/orcid"
                provider:
                    orcid:
                        authorization-uri: https://orcid.org/oauth/authorize
                        token-uri: https://orcid.org/oauth/token
                        user-info-uri: https://orcid.org/oauth/userinfo
                        user-name-attribute: sub

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
        org.springframework.web.client.RestTemplate: DEBUG







